'use strict';
module.exports = function(apiRoutes) {
  var post = require('../controllers/postController');

  // Post Routes
  apiRoutes.get('/posts', post.read_all_posts);
  apiRoutes.get('/pages', post.read_all_page_posts);
  apiRoutes.get('/page/:pageId', post.read_a_page_with_posts);
  apiRoutes.get('/user/page', post.get_page_for_user);
  apiRoutes.post('/page/:pageId', post.update_page);
  apiRoutes.post('/likePage', post.like_page);
  apiRoutes.post('/dislikePage', post.dislike_page);
  apiRoutes.post('/reactPost', post.react_post);
  apiRoutes.post('/likePost', post.like_post);
  apiRoutes.post('/dislikePost', post.dislike_post);
  apiRoutes.post('/likePostPhoto', post.like_post_photo);
  apiRoutes.post('/dislikePostPhoto', post.dislike_post_photo);
  apiRoutes.post('/likePostVideo', post.like_post_video);
  apiRoutes.post('/dislikePostVideo', post.dislike_post_video);
  apiRoutes.post('/likeComment', post.like_comment);
  apiRoutes.post('/dislikeComment', post.dislike_comment);
  apiRoutes.get('/page/:pageId/post/:postId', post.read_a_page_post);
  apiRoutes.get('/photo/:id', post.get_post_by_photo);
  apiRoutes.get('/adminposts', post.admin_read_all_posts);
  apiRoutes.get('/adminpageposts', post.admin_read_all_page_posts);
  apiRoutes.get('/adminpages', post.admin_read_all_pages);
  apiRoutes.get('/posts/:postId', post.read_a_post);
  apiRoutes.get('/postForEdit/:postId', post.read_a_post_for_edit);
  apiRoutes.get('/comments/:postId', post.get_all_comments);
  apiRoutes.post('/posts', post.create_a_post);
  apiRoutes.post('/postWithPage', post.create_a_post_and_page);
  apiRoutes.post('/editpost/:postId', post.edit_a_post);
  apiRoutes.delete('/posts/:postId', post.delete_a_post);
  apiRoutes.delete('/pages/:pageId', post.delete_a_page);
  apiRoutes.get('/flagcomment/:commentId', post.flag_a_comment);
  apiRoutes.post('/flagcommentreason/:commentId', post.flag_a_comment_reason);
  apiRoutes.get('/unflagcomment/:commentId', post.unflag_a_comment);
  apiRoutes.delete('/comments/:commentId', post.delete_a_comment);
  apiRoutes.post('/replycomment/:commentId', post.reply_a_comment);
  apiRoutes.delete('/deletereply/:replyId', post.delete_a_reply);
  apiRoutes.post('/flagreply/:replyId', post.flag_a_reply);
  apiRoutes.get('/unflagreply/:replyId', post.unflag_a_reply);
  apiRoutes.get('/flagpost/:postId', post.flagpost);
  apiRoutes.get('/flagpage/:pageId', post.flagpage);
  apiRoutes.post('/flagpostreason/:postId', post.flagpostreason);
  apiRoutes.post('/reportpagereason/:pageId', post.reportpagereason);
  apiRoutes.get('/unflagpost/:postId', post.unflagpost);
  apiRoutes.get('/unflagpage/:pageId', post.unflagpage);
  apiRoutes.get('/adminpost/:postId', post.admin_read_a_post);
  apiRoutes.get('/render/:postId', post.renderpost);
  apiRoutes.get('/renderPagePost/:postId', post.renderpagepost);
  apiRoutes.get('/renderPage/:pageId', post.renderpage);
  apiRoutes.post('/subscribe/:postId', post.subscribe);
  apiRoutes.post('/subscribePage/:pageId', post.subscribePage);
};
